### ISSUE TITLE
不能用了。。

### ISSUE THREAD

**Issue by lengyanwl** [shuo0261/edge-tts-web-interface#1]
报错信息：
aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url='wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4&ConnectionId=8203ebc7d47c49e1a37bbced96793ddc'

**Comment by shuo0261** [comment]
我测试正常的，你可以试着自己搭建一下，看看是否正常，这个错误是Bing提示的

**Comment by shuo0261** [comment]
> 报错信息： aiohttp.client_exceptions.WSServerHandshakeError： 403， message='无效响应状态'， url='wss：//speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1？TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4&ConnectionId=8203ebc7d47c49e1a37bbced96793ddc'

我测试正常的，你可以试着自己搭建一下，看看是否正常，这个错误是Bing提示的
